openapi: 3.0.1
info:
  title: 'https://api.cyble.ai API'
  description: 'https://api.cyble.ai API'
  version: v1.0
servers:
  - url: 'https://api.cyble.ai'
paths:
  /appolo/api/v1/y/alerts:
    description: Provides operations to manage alerts
    POST:
      summary: Post alerts
      operationId: Post.appolo.api.v1.y.alerts
      requestBody:
        required: true  # Request body is required
        content:
          application/json:
            schema:
              type: object
              properties:
                "companyUuid": "a0959c21-ec02-47cc-8d4b-224fd9adecb9"
                  type: string
                orderBy:
                  type: array
                  items:
                    type: object
                    properties:
                      created_at:
                        type: string
                select:
                  type: object
                  properties:
                    alert_group_id:
                      type: boolean
                    archive_date:
                      type: boolean
                    archived:
                      type: boolean
                    assignee_id:
                      type: boolean
                    assignment_date:
                      type: boolean
                    created_at:
                      type: boolean
                    data_id:
                      type: boolean
                    deleted_at:
                      type: boolean
                    description:
                      type: boolean
                    hash:
                      type: boolean
                    id:
                      type: boolean
                    metadata:
                      type: boolean
                    risk_score:
                      type: boolean
                    service:
                      type: boolean
                    severity:
                      type: boolean
                    status:
                      type: boolean
                    tags:
                      type: boolean
                    updated_at:
                      type: boolean
                    user_severity:
                      type: boolean
                withDataMessage:
                  type: boolean
                skip: 0
                  type: integer
                take: 10
                  type: integer
                where:
                  type: object
                  properties:
                    created_at:
                      type: object
                      properties:
                        gte:
                          type: string
                        lte:
                          type: string
                    service:
                      type: object
                      properties:
                        in:
                          type: array
                          items:
                            type: string
                    severity:
                      type: object
                      properties:
                        in:
                          type: array
                          items:
                            type: string
                    status:
                      type: object
                      properties:
                        in:
                          type: array
                          items:
                            type: string
      responses:
        '404':
          description: Not Found
          headers:
            CF-Cache-Status:
              schema:
                type: string
            X-Content-Type-Options:
              schema:
                type: string
            CF-RAY:
              schema:
                type: string
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
x-ms-generated-by:
  toolName: Dev Proxy
  toolVersion: 0.17.1
