openapi: 3.0.1
info:
  title: CyberArk Events API
  version: 1.0.0
servers:
  - url: https://wiproidamcoe.privilegecloud.cyberark.com/PasswordVault/API/
paths:
  /Events:
    get:
      summary: Get CyberArk Events
      description: Retrieve security alerts, audit logs, and incident reports from CyberArk Privilege Cloud.
      parameters:
        - name: fromUpdateDate
          in: query
          description: Filter events from a specific UNIX timestamp (in seconds).
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter events by status (e.g., open, closed).
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of CyberArk events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
